### ISSUE TITLE
Question: Is there an equivalent to the cites command?

### ISSUE THREAD

**Issue by ThiloteE** [zepinglee/citeproc-lua#10]
^
desired outcome:

something relative to: https://tex.stackexchange.com/questions/18910/multiple-citations-with-pages-using-biblatex?noredirect=1&lq=1

I have read `In other packages, several commands are provided for producing citations in different styles such as \citet, \citep, \parencite, and \footnotecite. In citation-style-language package, however, the format of citations is fixed as formatted in CSL style
and it is impossible to select another format without modifying the .csl style file` in the documentation.

Does this mean, it is absolutely impossible to cite multiple citations with pages?

**Comment by zepinglee** [comment]
The `citeproc` is fully capable of processing multiple cites with pages in a single citation. I got stuck when trying to implement the LaTeX interface `\cites` with `expl3`. It is mainly because this command receives undetermined number of braced arguments and I'm not sure it is a good design for user interface. I'll post a question to tex.sx for help.

**Comment by ThiloteE** [comment]
Thank you :-)

To clarify, for all the people that are not familiar with the cites command and that might look at this at a later point in time, I am looking forward to have output that roughly resembles something like this:

![image](https://user-images.githubusercontent.com/73715071/152468683-550ce45f-abad-43a6-a2b8-ac052d405677.png)

or

![image](https://user-images.githubusercontent.com/73715071/152469047-8787cc09-bd2c-4ef1-9b75-18ab401557cf.png)

Of course, it depends on the style.
