### ISSUE TITLE
Option to stop citation appearing in bibliography?

### ISSUE THREAD

**Issue by nickw2066** [zepinglee/citeproc-lua#31]
Hi,
Is there an option to cite something but stop it appearing in the bibliography?
Like [this](https://brianbuccola.com/how-to-cite-in-latex-without-the-citation-appearing-in-the-bibliography/) Biblatex feature?
```
\documentclass{article}
\usepackage[style=authoryear]{biblatex}
\addbibresource{/path/to/references.bib}
\DeclareBibliographyCategory{ignore}
\addtocategory{ignore}{johnson2015}
\addtocategory{ignore}{doe1986}

\begin{document}

\cite{johnson2015},
\cite{smith2015},
\cite{doe1986},
\cite{samson2012}

\printbibliography[notcategory=ignore]
\end{document}
```
I need to cite a book review but it's not meant to appear in my bibliography.
Thanks,
Nick

**Comment by zepinglee** [comment]
It's reasonable and I'll prioritize this feature.

**Comment by zepinglee** [comment]
I've just added the `type`, `nottype`, `keyword`, `notkeyword`, `category`, and `notcategory` options to `\printbibliography` as well as `\DeclareBibliographyCategory` and `\addtocategory` commands. All of them work in the same way as in `biblatex`. The `filter` and `\defbibfilter`  in `biblatex` are  not implemented at the moment.

**Comment by bemilton** [comment]
@zepinglee Could you add a capability to define `title` when selecting by `category`? For example: [there's an overleaf example here](https://www.overleaf.com/learn/latex/Questions/Creating_multiple_bibliographies_in_the_same_document#Using_categories) using package `biblatex`.

Unfortunately, with `citation-style-language` package there is an (ignored) error due to `title` option: 

`! LaTeX Error: The key 'csl/bibliography/title' is unknown and is being
(LaTeX)        ignored.`

The rendered PDF simply repeats "References" (when using `\documentclass[11pt]{article}`) per each `\printbibliography[category={phys}, title={test}]`.

**Comment by zepinglee** [comment]
@bemilton I've just added the `heading` and `title` options and the above example works fine.

**Comment by bemilton** [comment]
@zepinglee Brilliant, thank you for rapid solution. By the way -- it is an excellent tex package!
