### ISSUE TITLE
I can't get citeproc-lua to work on Texifier for macOS

### ISSUE THREAD

**Issue by PunkFafa** [zepinglee/citeproc-lua#47]
I've installed everything correctly. I've read the package documentation from top to bottom thrice. And I just can't make the package work. Every time I run a super simple code I get from 177 to 186 errors saying things like:

- citation-style-language error: "incompatible-package". The 'babelbib' package is incompatible with `citation-style-language'.
- citation-style-language error: "incompatible-package". The 'biblatex' package is incompatible with `citation-style-language'.
- citation-style-language error: "incompatible-package". The 'bibtopic' package is incompatible with `citation-style-language'.
- citation-style-language error: "incompatible-package". The 'bibunits' package is incompatible with `citation-style-language'.
- citation-style-language error: "incompatible-package". The 'chapterbib' package is incompatible with `citation-style-language'.
- citation-style-language error: "incompatible-package". The 'cite' package is incompatible with `citation-style-language'.
- LaTeX error: "kernel/property-unknown". 
- The key property '.prop_put:N' is unknown.
- 'csl/cite-item/prefix': this property is not defined.
- AND MANY, MANY MORE.

The fact is that I'm not using any of those packages (at least not intentionally). This is my code:

```
\documentclass{article}

\usepackage[style = apa]{citation-style-language}

\addbibresource{thesis-bibliography.json}

\begin{document}

\cite[prefix = {See }, page = 42]{russellDenoting1905}
\printbibliography

\end{document}
```

**Additional information**
- TeX distribution: MacTeX 2023
- Package citation-style-language
- LaTeX engine: TexpadTeX

**Comment by zepinglee** [comment]
Are you runing TexpadTeX with Texifier? Unfortunately I can't test it since it requires a license key.

The following are code lines related to `incompatible-package` error. The `\msg_error:nnn` is added to the beginning of loading each package, respectively. It should be skipped if the package is not loaded.

https://github.com/zepinglee/citeproc-lua/blob/ab3ce712cc92073f12be26ff0b22b30eb906092d/latex/citation-style-language.sty#L23-L32

**Comment by PunkFafa** [comment]
Any idea of how I can make it work? Code is as you described it.

**Comment by zepinglee** [comment]
> * LaTeX error: "kernel/property-unknown".
> * The key property '.prop_put:N' is unknown.
> * 'csl/cite-item/prefix': this property is not defined.

These errors are possibly because of an outdated LaTeX3 kernel. The `.prop_put:N` was added on 2019-01-31. I'm afraid it's hard to make this package compatible with versions as early as that.

> Any idea of how I can make it work? Code is as you described it.

Not likely. The TexpadTeX documentation says:

> Packages that rely on external tools such as pygments, gnuplot, R are not currently compatible.

> We plan to add LuaTeX compatible extensions to TexpadTeX in the future, but that will take some time.

The citeproc-lua packages requires running external command when working with pdfTeX/XeTeX or a Lua interpreter with LuaTeX. Yet TexpadTeX supports neither of them. Perhaps you can contact the texifier team.
