### ISSUE TITLE
csl.sty fails with other styles

### ISSUE THREAD

**Issue by simifilm** [zepinglee/citeproc-lua#7]
I tried `example.tex` with other .csl styles, but without luck. For example, if I replace `plain`with [Zeitschrift für Fantastikforschung (Deutsch)](https://www.zotero.org/styles/zeitschrift-fur-fantastikforschung) which I wrote, the compilation produces all kinds of errors and completely borked pdf (.log attached)
[example.log](https://github.com/zepinglee/citeproc-lua/files/7718282/example.log)
.

**Comment by zepinglee** [comment]
It is because this `.csl` style requires `locales-de-DE.xml` which is not installed to TEXMF. You can copy one from [citation-style-language/locales](https://github.com/citation-style-language/locales) to the working directory. After that the example works for me. I'm planning to pack all the locale files in [citation-style-language/locales](https://github.com/citation-style-language/locales) together when publishing to CTAN and there will be no need to perform the copying. 

Currently the `module_error` function from LaTeX2e kernel (`ltluatex.dtx`) is used to raise an error. This function always prints the stack traceback, which may be very long and makes it difficult to read. I'll figure out a way to give cleaner error messages.

**Comment by simifilm** [comment]
With `locales-de-DE.xml` it works. Thanks!
